WebApi/Controllers/ListsController.cs
using BLL.DTO;
using BLL.Interfaces;
using BLL.Services.FuncSignatures;
using Microsoft.AspNetCore.Mvc;
using WebApi.Models;

namespace WebApi.Controllers
{
    public class ListsController : Controller
    {
        private readonly ITraineeService _traineeService;
        private readonly IProjectService _projectService;
        private readonly IDirectionService _directionService;
        public ListsController(ITraineeService traineeService,
            IProjectService projectService,
            IDirectionService directionService
            )
        {
            _traineeService = traineeService;
            _projectService = projectService;
            _directionService = directionService;
        }

        [HttpGet]
        [Route("/lists-dir-prj")]
        public async Task<IActionResult> Index(
            string searchName, bool descending, 
            int index, int pageSize = 10, 
            SortingKey sortOrder = SortingKey.Name, 
            StateChoose choose = StateChoose.Directions)
        {  
            ListsViewModel model;
            var pageState = new PageListState
            {
                SearchName = searchName,
                Descending = descending,
                CurrentPage = index,
                PageSize = pageSize,
                SortOrder = sortOrder,
                Choose = choose
            };
            var trainees = await _traineeService.GetAll();
            if (choose == StateChoose.Directions)
            {
                var directionsGet = await _directionService.GetAll(
                    new ServicesGetAllParameters<DirectionDTO>(sortOrder, descending, index, pageSize, searchName));
                var directions = directionsGet.Entities;    
                pageState.PageMax = directionsGet.PageCount;
                model = new ListsViewModel
                {
                    Directions = directions,
                    PageListState = pageState,
                    Trainees = trainees
                };
            } else
            {
                var projectsGet = await _projectService.GetAll(
                    new ServicesGetAllParameters<ProjectDTO>(sortOrder, descending, index, pageSize, searchName));
                var projects = projectsGet.Entities;
                pageState.PageMax = projectsGet.PageCount;
                model = new ListsViewModel
                {
                    Projects = projects,
                    PageListState = pageState,
                    Trainees = trainees
                };
            }
            
            return View(model);
        }
    }
}

WebApi/Controllers/TraineeController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using PracticeTest.Controllers;
using WebApi.Models;
using WebApi.SignalRHubs;

namespace WebApi.Controllers
{
    public class TraineeController : Controller
    {
        private readonly ITraineeService _traineeService;
        private readonly IProjectService _projectService;
        private readonly IDirectionService _directionService;
        private readonly ILogger<HomeController> _logger;
        private readonly IHubContext<NotificationHub> _hubContext;
        private readonly IMapper _mapper;
        public TraineeController(ITraineeService traineeService, 
            IProjectService projectService, 
            IDirectionService directionService,
            ILogger<HomeController> logger,
            IHubContext<NotificationHub> hubContext,
            IMapper mapper
            )
        {
            _traineeService = traineeService;
            _projectService = projectService;
            _directionService = directionService;
            _logger = logger;
            _hubContext = hubContext;
            _mapper = mapper;
        }

        [HttpGet]
        [Route("/trainee-create")]
        public async Task<ActionResult> Create()
        {
            ViewBag.Projects = new SelectList(await _projectService.GetAll(), "Id", "Name");
            ViewBag.Directions = new SelectList(await _directionService.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateProject(CreateViewModel model)
        {
            if (model.Project != null)
            {
                try
                {
                    await _projectService.Create(model.Project);
                    TempData["Message"] = "Проект создан";
                }
                catch (Exception ex)
                {
                    TempData["Message"] = ex.Message;
                }
            }     
            return RedirectToAction("Create");
        }

        [HttpPost]
        public async Task<IActionResult> CreateDirection(CreateViewModel model)
        {
            if (model.Direction != null)
            {
                try
                {
                    await _directionService.Create(model.Direction);
                    TempData["Message"] = "Направление создано";
                }
                catch (Exception ex)
                {
                    TempData["Message"] = ex.Message;
                }
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        [Route("/trainee-create")]
        public async Task<ActionResult> CreateAsync(CreateViewModel model)
        {
            string message = "Форма успешно отправлена";
            try
            {
                var traineeDto = model.Trainee;

                TraineeDTO trainee;
                traineeDto.Project = model.Project;
                traineeDto.Direction = model.Direction;
                await _traineeService.Create(traineeDto);
                trainee = await _traineeService.Retrieve(traineeDto.Email);
                traineeDto.Project = trainee.Project;
                traineeDto.Direction = trainee.Direction;
                traineeDto.Id = trainee.Id;
                TempData["Message"] = message;

                var notification = _mapper.Map<Dictionary<string, string>>(traineeDto);
                await _hubContext.Clients.All.SendAsync("ReceiveCreate", notification);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToAction("Create");
        }

        [HttpPost]
        [Route("/trainees")]
        public async Task<ActionResult> EditAsync(
            int traineeId, string traineeName, string traineeSurname, 
            GenderDTO traineeGender, string traineeEmail, string traineePhone,
            DateOnly traineeBirthday)
        {
            var traineeDto = new TraineeDTO
            {
                Id = traineeId,
                Name = traineeName,
                Surname = traineeSurname,
                Gender = traineeGender,
                Email = traineeEmail,
                Phone = traineePhone,
                BirthDay = traineeBirthday,
            };
            string message = "Форма успешно отправлена";
            try
            {
                await _traineeService.Update(traineeDto);
                TempData["Message"] = message;
                var notification = _mapper.Map<Dictionary<string, string>>(
                    await _traineeService.Retrieve(traineeDto.Id));
                await _hubContext.Clients.All.SendAsync("ReceiveEdit", notification);
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToAction("List");
        }

        [HttpGet]
        [Route("/trainees-list")]
        public async Task<ActionResult> List(int directionId = -1, int projectId = -1)
        {
            var trainees = await _traineeService.GetAll();
            var directions = await _directionService.GetAll();
            var projects = await _projectService.GetAll();
            try
            {
                if (directionId != -1)
                {
                    trainees = _traineeService.FilterByDirections(trainees, directionId);
                }
                if (projectId != -1)
                {
                    trainees = _traineeService.FilterByProjects(trainees, projectId);
                }
            } catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            TraineeListViewModel model = new TraineeListViewModel
            {
                Trainees = trainees,
                Directions = directions,
                Projects = projects
            };
            return View(model);
        }
    }
}

WebApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticeTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticeTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticeTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainee" asp-action="Create">Добавить стажера</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lists" asp-action="Index">Направления и проекты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trainee" asp-action="List">Стажеры</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>